name: Deploy to GH Pages on push to develop

on:
  push:
    branches: 
    - develop

jobs:
  push_gh_pages:
    name: pushing to github pages
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
        with:
          ref: develop
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install
      - run: npm run build
        env: 
          PRISMIC_REPOSITORY_NAME: ${{ secrets.PRISMIC_REPOSITORY_NAME }}
          PRISMIC_ACCESS_TOKEN: ${{ secrets.PRISMIC_ACCESS_TOKEN }}
      - run: cp CNAME public/
      - name: GitHub Pages Deploy
        uses: maxheld83/ghpages@v0.2.1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        env:
          BUILD_DIR: public/
